### PR TITLE
Creating feature for Donna to fetch results from knowledge base for user query provided and summarizing results ( Pinecone + GPT)

### PR DESCRIPTION
**Pull request by parisha6**
1. Made changes in frontend for Donna to identify if a  query requesting information from knowledge base
2. Integrating Pinecone API in backend to fetch top 3 results from the RAG vector datasbase of uploaded documents
3. Included a code to summarize the results obtained through Pinecone using GPT.
4. Made changes in backend to send the summarized results obtained to frontend for Donna to display and voice those results.

Please approve the PR.

### CODE REVIEW

**Review by usha8719 — CHANGES_REQUESTED** [review]
Can you try to change .env to env.example ?

**Comment by parisha6** [comment]
> Can you try to change .env to env.example ?

Hi Usha- I did those changed. Please verify now

**Review by iAbhi001 — APPROVED** [review]
Good work, I think it matches our expectations !!

**Review by swetha-r13 — APPROVED** [review]
Approved

**Review by ashutoshm97 — APPROVED** [review]
Great work Parisha! It's good that the PineCone API is seemlessly working and providing us with better optimized results.

**Pull request merged**
