### PR TITLE
For Donna Frontend created ChatContext hook, UI components, and Tailwind styling

### PR DESCRIPTION
**Pull request by parisha6**
This PR introduces the following implementations:

1. Context Logic: Implemented useChat hook and ChatProvider for managing chat messages and interacting with the backend API.
2. UI Component: Created a UI component that handles user input in text and audio and displays response messages, including support for voice input functionality.
3. Tailwind CSS Integration: Integrated Tailwind CSS for a responsive design, enhancing the overall visual appeal.
4. Global Styles: Applied global styles in index.css, including font imports, viewport sizing, and background gradients for improved aesthetics.
5. Green Screen Mode: Added support for a "green screen" mode, allowing for alternate background styling based on user preference.

These implementation establishes a  base for the virtual assistant interface and the overall user experience.

### CODE REVIEW

**Review by swetha-r13 — APPROVED** [review]

**Comment by ashutoshm97** [comment]
Approved

**Comment by usha8719** [comment]
Approved

**Comment by zeshengchen** [comment]
Why this pull request was complete without getting all approvals from other group members?

**Comment by parisha6** [comment]
Hello Professor 
One of the teammate merged it mistakenly while approving PR. I have set rule in repository to not allow direct push to main branch unless 4 approvals are obtained on a PR. In future I guess it will restrict from such commits. 

Best Regards, 
Parisha Desai

**Comment by parisha6** [comment]
@iAbhi001 please review

**Pull request merged**
