### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by iAbhi001**

### CODE REVIEW

**Comment by iAbhi001** [comment]
I created this PR to implement File Fetching and SMTP mail service for Donna

**Review by ashutoshm97 — APPROVED** [review]
The script is following Pep-8 standards and the script is well documented

**Review by usha8719 — APPROVED** [review]
Well formatted and good work on smtp too

**Review by swetha-r13 — APPROVED** [review]

**Review by parisha6 — APPROVED** [review]
Approved

**Pull request merged**
