### PR TITLE
Implemented the necessary handling as per Professors past comments captured below:

### PR DESCRIPTION
**Pull request by parisha6**
1. Put user name, password, and the link to db in the environment variables in ".env" file.
2. Do not directly upload ".env" file, instead uploading ".env_example" file and put something like: DATABASE_URL=
...
in ".env_example" file

### CODE REVIEW

**Review by swetha-r13 — APPROVED** [review]

**Comment by ashutoshm97** [comment]
Makes sense now. Approved

**Comment by usha8719** [comment]
looks good like professor mentioned

**Comment by zeshengchen** [comment]
@usha8719 please wait to merge the pull request until the pull request gets all approvals!

**Comment by usha8719** [comment]
Sorry Professor, my bad! I accidentally merged the pull request. It won't repeat again, and I will make sure my other group members review these pull requests and will take their feedback.

**Comment by parisha6** [comment]
@iAbhi001 please review

**Pull request merged**
