### PR TITLE
Adding Latest version of UI.Jsx file in Frontend folder with cosmetic changes

### PR DESCRIPTION
**Pull request by swetha-r13**
Here are the cosmetic changes made to the code:

1.Loader Addition:

Added a spinning loader to indicate ongoing actions like transcription or API calls.
2.UI Component Background:

Changed the background color of some UI components to improve visual appeal and user focus.
3.Alignment of Buttons:

Adjusted the button alignment to make the layout more user-friendly and organized.
4.Large Text Area Addition:

Added a larger text area for user input, making it easier to compose longer messages or view content clearly.

### CODE REVIEW

**Comment by iAbhi001** [comment]
I am approving cosmetic changes and they are nice !! Excited to see them in Action !!

**Review by iAbhi001 — APPROVED** [review]
I am approving your cosmetic changes, it seem really good. Excited to see them in Action !!

**Review by usha8719 — APPROVED** [review]
UI looks better now. Approving the PR

**Review by parisha6 — APPROVED** [review]
UI looks better now with implementation of these changes. Approved..

**Pull request merged**
