### PR TITLE
Adding updated version of frontend and backend with the email and reminder features 

### PR DESCRIPTION
**Pull request by usha8719**
1. Added code in the frontend for fetching the date and time from the user prompt to create the json body request for setting up the reminder
2. Calling the microsoft graph api in the backend to create an event in the user calendar
3. Added code for fetching the email and the body for the email from the user prompt
4. Creating the json request with the email, body 
5. From the sendEmail endpoint in the backend, an api call will trigger through graph api for sending the email

### CODE REVIEW

**Review by parisha6 — APPROVED** [review]
Approved. Verified the functionality is implemented well in UI.jsx in frontend and index.js in Backend.

**Comment by usha8719** [comment]
Due to large files in the folder, I had to use lfs and create a new branch donna_ver4 which has the updated code. I have created this pull request to merge it into the main branch professor. I have mentioned all the changes I have applied in the Donna_ver4 in the description.

**Comment by zeshengchen** [comment]
This is what I saw for your changes:

image

**Review by iAbhi001 — APPROVED** [review]

**Comment by iAbhi001** [comment]
I think it's good, keep progressing !!

**Review by swetha-r13 — APPROVED** [review]
Approved t

**Pull request merged**
